[package]
name = "fuzzrs"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
futures = "0.3.30"
ratatui = "0.28.1"
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["full"] }
